// Generated by gencpp from file arm_control/command.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_COMMAND_H
#define ARM_CONTROL_MESSAGE_COMMAND_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control
{
template <class ContainerAllocator>
struct command_
{
  typedef command_<ContainerAllocator> Type;

  command_()
    : pose()  {
      pose.assign(0);
  }
  command_(const ContainerAllocator& _alloc)
    : pose()  {
  (void)_alloc;
      pose.assign(0);
  }



   typedef boost::array<int32_t, 6>  _pose_type;
  _pose_type pose;





  typedef boost::shared_ptr< ::arm_control::command_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::command_<ContainerAllocator> const> ConstPtr;

}; // struct command_

typedef ::arm_control::command_<std::allocator<void> > command;

typedef boost::shared_ptr< ::arm_control::command > commandPtr;
typedef boost::shared_ptr< ::arm_control::command const> commandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::command_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::command_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'arm_control': ['/home/ben/gripper_proj_2/src/arm_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::command_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::command_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::command_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::command_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "1a1a3549ea1fbd90af851784fda8677a";
  }

  static const char* value(const ::arm_control::command_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x1a1a3549ea1fbd90ULL;
  static const uint64_t static_value2 = 0xaf851784fda8677aULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/command";
  }

  static const char* value(const ::arm_control::command_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::command_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[6] pose\n\
";
  }

  static const char* value(const ::arm_control::command_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::command_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.pose);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct command_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::command_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::command_<ContainerAllocator>& v)
  {
    s << indent << "pose[]" << std::endl;
    for (size_t i = 0; i < v.pose.size(); ++i)
    {
      s << indent << "  pose[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.pose[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_COMMAND_H
