// Generated by gencpp from file arm_control/position.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_POSITION_H
#define ARM_CONTROL_MESSAGE_POSITION_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control
{
template <class ContainerAllocator>
struct position_
{
  typedef position_<ContainerAllocator> Type;

  position_()
    : point()  {
      point.assign(0.0);
  }
  position_(const ContainerAllocator& _alloc)
    : point()  {
  (void)_alloc;
      point.assign(0.0);
  }



   typedef boost::array<float, 4>  _point_type;
  _point_type point;





  typedef boost::shared_ptr< ::arm_control::position_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::position_<ContainerAllocator> const> ConstPtr;

}; // struct position_

typedef ::arm_control::position_<std::allocator<void> > position;

typedef boost::shared_ptr< ::arm_control::position > positionPtr;
typedef boost::shared_ptr< ::arm_control::position const> positionConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::position_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::position_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'arm_control': ['/home/ben/gripper_proj_2/src/arm_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::position_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::position_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::position_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::position_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "c8e7818df37db2cf138689cbda172d04";
  }

  static const char* value(const ::arm_control::position_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xc8e7818df37db2cfULL;
  static const uint64_t static_value2 = 0x138689cbda172d04ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/position";
  }

  static const char* value(const ::arm_control::position_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::position_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32[4] point\n\
";
  }

  static const char* value(const ::arm_control::position_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::position_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.point);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct position_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::position_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::position_<ContainerAllocator>& v)
  {
    s << indent << "point[]" << std::endl;
    for (size_t i = 0; i < v.point.size(); ++i)
    {
      s << indent << "  point[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.point[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_POSITION_H
