// Generated by gencpp from file arm_control/TOF_sensor_data.msg
// DO NOT EDIT!


#ifndef ARM_CONTROL_MESSAGE_TOF_SENSOR_DATA_H
#define ARM_CONTROL_MESSAGE_TOF_SENSOR_DATA_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace arm_control
{
template <class ContainerAllocator>
struct TOF_sensor_data_
{
  typedef TOF_sensor_data_<ContainerAllocator> Type;

  TOF_sensor_data_()
    : range_reading()
    , lux_reading()  {
      range_reading.assign(0);

      lux_reading.assign(0.0);
  }
  TOF_sensor_data_(const ContainerAllocator& _alloc)
    : range_reading()
    , lux_reading()  {
  (void)_alloc;
      range_reading.assign(0);

      lux_reading.assign(0.0);
  }



   typedef boost::array<int32_t, 3>  _range_reading_type;
  _range_reading_type range_reading;

   typedef boost::array<float, 3>  _lux_reading_type;
  _lux_reading_type lux_reading;





  typedef boost::shared_ptr< ::arm_control::TOF_sensor_data_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::arm_control::TOF_sensor_data_<ContainerAllocator> const> ConstPtr;

}; // struct TOF_sensor_data_

typedef ::arm_control::TOF_sensor_data_<std::allocator<void> > TOF_sensor_data;

typedef boost::shared_ptr< ::arm_control::TOF_sensor_data > TOF_sensor_dataPtr;
typedef boost::shared_ptr< ::arm_control::TOF_sensor_data const> TOF_sensor_dataConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::arm_control::TOF_sensor_data_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::arm_control::TOF_sensor_data_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace arm_control

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'arm_control': ['/home/ben/gripper_proj_2/src/arm_control/msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::TOF_sensor_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::arm_control::TOF_sensor_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::TOF_sensor_data_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::arm_control::TOF_sensor_data_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::TOF_sensor_data_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::arm_control::TOF_sensor_data_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::arm_control::TOF_sensor_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "3c37e3e2c7851686cb8c295f62489702";
  }

  static const char* value(const ::arm_control::TOF_sensor_data_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x3c37e3e2c7851686ULL;
  static const uint64_t static_value2 = 0xcb8c295f62489702ULL;
};

template<class ContainerAllocator>
struct DataType< ::arm_control::TOF_sensor_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "arm_control/TOF_sensor_data";
  }

  static const char* value(const ::arm_control::TOF_sensor_data_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::arm_control::TOF_sensor_data_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[3] range_reading\n\
float32[3] lux_reading\n\
";
  }

  static const char* value(const ::arm_control::TOF_sensor_data_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::arm_control::TOF_sensor_data_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.range_reading);
      stream.next(m.lux_reading);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct TOF_sensor_data_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::arm_control::TOF_sensor_data_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::arm_control::TOF_sensor_data_<ContainerAllocator>& v)
  {
    s << indent << "range_reading[]" << std::endl;
    for (size_t i = 0; i < v.range_reading.size(); ++i)
    {
      s << indent << "  range_reading[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.range_reading[i]);
    }
    s << indent << "lux_reading[]" << std::endl;
    for (size_t i = 0; i < v.lux_reading.size(); ++i)
    {
      s << indent << "  lux_reading[" << i << "]: ";
      Printer<float>::stream(s, indent + "  ", v.lux_reading[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARM_CONTROL_MESSAGE_TOF_SENSOR_DATA_H
