# This Python file uses the following encoding: utf-8
"""autogenerated by genpy from trainer/color_sensor_data.msg. Do not edit."""
import sys
python3 = True if sys.hexversion > 0x03000000 else False
import genpy
import struct


class color_sensor_data(genpy.Message):
  _md5sum = "7c8cfe28df9aa44956a941b8c260653a"
  _type = "trainer/color_sensor_data"
  _has_header = False #flag to mark the presence of a Header object
  _full_text = """int32[4] rgb_values
int32 color_temp
float32 lux
"""
  __slots__ = ['rgb_values','color_temp','lux']
  _slot_types = ['int32[4]','int32','float32']

  def __init__(self, *args, **kwds):
    """
    Constructor. Any message fields that are implicitly/explicitly
    set to None will be assigned a default value. The recommend
    use is keyword arguments as this is more robust to future message
    changes.  You cannot mix in-order arguments and keyword arguments.

    The available fields are:
       rgb_values,color_temp,lux

    :param args: complete set of field values, in .msg order
    :param kwds: use keyword arguments corresponding to message field names
    to set specific fields.
    """
    if args or kwds:
      super(color_sensor_data, self).__init__(*args, **kwds)
      #message fields cannot be None, assign default values for those that are
      if self.rgb_values is None:
        self.rgb_values = [0] * 4
      if self.color_temp is None:
        self.color_temp = 0
      if self.lux is None:
        self.lux = 0.
    else:
      self.rgb_values = [0] * 4
      self.color_temp = 0
      self.lux = 0.

  def _get_types(self):
    """
    internal API method
    """
    return self._slot_types

  def serialize(self, buff):
    """
    serialize message into buffer
    :param buff: buffer, ``StringIO``
    """
    try:
      buff.write(_get_struct_4i().pack(*self.rgb_values))
      _x = self
      buff.write(_get_struct_if().pack(_x.color_temp, _x.lux))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize(self, str):
    """
    unpack serialized message in str into this message instance
    :param str: byte array of serialized message, ``str``
    """
    try:
      end = 0
      start = end
      end += 16
      self.rgb_values = _get_struct_4i().unpack(str[start:end])
      _x = self
      start = end
      end += 8
      (_x.color_temp, _x.lux,) = _get_struct_if().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill


  def serialize_numpy(self, buff, numpy):
    """
    serialize message with numpy array types into buffer
    :param buff: buffer, ``StringIO``
    :param numpy: numpy python module
    """
    try:
      buff.write(self.rgb_values.tostring())
      _x = self
      buff.write(_get_struct_if().pack(_x.color_temp, _x.lux))
    except struct.error as se: self._check_types(struct.error("%s: '%s' when writing '%s'" % (type(se), str(se), str(locals().get('_x', self)))))
    except TypeError as te: self._check_types(ValueError("%s: '%s' when writing '%s'" % (type(te), str(te), str(locals().get('_x', self)))))

  def deserialize_numpy(self, str, numpy):
    """
    unpack serialized message in str into this message instance using numpy for array types
    :param str: byte array of serialized message, ``str``
    :param numpy: numpy python module
    """
    try:
      end = 0
      start = end
      end += 16
      self.rgb_values = numpy.frombuffer(str[start:end], dtype=numpy.int32, count=4)
      _x = self
      start = end
      end += 8
      (_x.color_temp, _x.lux,) = _get_struct_if().unpack(str[start:end])
      return self
    except struct.error as e:
      raise genpy.DeserializationError(e) #most likely buffer underfill

_struct_I = genpy.struct_I
def _get_struct_I():
    global _struct_I
    return _struct_I
_struct_if = None
def _get_struct_if():
    global _struct_if
    if _struct_if is None:
        _struct_if = struct.Struct("<if")
    return _struct_if
_struct_4i = None
def _get_struct_4i():
    global _struct_4i
    if _struct_4i is None:
        _struct_4i = struct.Struct("<4i")
    return _struct_4i
